services:
  - type: web
    name: smart-ehs
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()' --workers=2 --threads=8 --timeout=120 -b 0.0.0.0:$PORT"
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
      # Cache SentenceTransformer model on your persistent disk:
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /opt/render/project/src/data/.models
      - key: HF_HOME
        value: /opt/render/project/src/data/.hfcache
      # Optional: pin Python
      - key: PYTHON_VERSION
        value: 3.11.9
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 10
